Repository lab-of-song/system-design-study, pull requests merged in 2024-12, with the labels that each got.

#2 [#1] 사용자 수에 따른 규모 확장성
  심화/Chapter 1/소민/README.md
  심화/Chapter 1/소민/images/clustering.png
  심화/Chapter 1/소민/images/partitioning.png
  심화/Chapter 1/소민/images/replication.png
  심화/Chapter 1/소민/images/sharding.png
  정리/Chapter 1/소민/README.md
Labels: 소민

#6 [#2] 개략적인 규모 추정
  심화/Chapter 2/소민/README.md
  정리/Chapter 2/소민/README.md
Labels: 소민

#4 [#1] 사용자 수에 따른 규모 확장성
  심화/Chapter 1/종호/README.md
  정리/Chapter 1/종호/README.md
Labels: 종호

#9 [#3] 시스템 설계 면접 공략법
  심화/Chapter 3/소민/README.md
  심화/Chapter 3/소민/images/create-node-edge.png
  심화/Chapter 3/소민/images/cypher.png
  심화/Chapter 3/소민/images/graph.png
  정리/Chapter 3/소민/README.md
  정리/Chapter 3/소민/images/detail-1.jpeg
  정리/Chapter 3/소민/images/detail-2.jpeg
  정리/Chapter 3/소민/images/overall.jpeg
Labels: 소민

#10 [#3] 시스템 설계 면접 공략법
  정리/Chapter 3/은주/README.md
  정리/Chapter 3/은주/image.png
Labels: 은주
